# Rouler plusieurs versions de MySQL
# Auteur: Alain Boudreault
# Date: 2020.02.18

version: '3'

services:

  mysql-dev:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: chetledipa
      MYSQL_DATABASE: uneapp
    ports:
      - "3308:3306"
  
  admin:    
    image: adminer    
    ports:      
      - "8080:8080"
  
  mysql-5.7:
    image: mysql:5.7.27
    environment:
      MYSQL_ROOT_PASSWORD: chetledipa
      MYSQL_DATABASE: uneautreappp
    ports:
      - "3309:3306"