version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      - WORDPRESS_DB_HOST=maBD
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=memesitumepetteslafacejtelediraipas
      - WORDPRESS_DB_NAME=wp
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    container_name: maBD
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=memesitumepetteslafacejtelediraipas
      #MYSQL_DATABASE: mysql
      #MYSQL_USER: root
      #MYSQL_PASSWORD: password
      #MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  myadmin:
    image: phpmyadmin
    container_name: myadmin
    ports:
      - "88:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=memesitumepetteslafacejtelediraipas
      - PMA_HOST=maBD

volumes:
  wordpress:
  db: