version: "3.9"
services:
  cie_bd:
    image: mariadb:10.5
    ports:
        - "3333:3306"
    environment:
        - "MYSQL_DATABASE=cie_abc"
        - "MYSQL_RANDOM_ROOT_PASSWORD=1"
        - "MYSQL_USER=cieuser"
        - "MYSQL_PASSWORD=donttell"
    volumes:
    - ./cie_data3/:/var/lib/mysql

  wordpress:
    image: wordpress:5.6.2
    ports:
      - "88:80"
    environment:
        - "WORDPRESS_DB_HOST=cie_bd"
        - "WORDPRESS_DB_USER=cieuser"
        - "WORDPRESS_DB_PASSWORD=donttell"
        - "WORDPRESS_DB_NAME=cie_abc"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8081:80"
    environment:
        - "PMA_HOST=cie_bd"
        - "PMA_USER=cieuser"
        - "PMA_PASSWORD=donttell"