version: "3.9"
 
services:
  serveurweb:
    image: nginx
    container_name: serveurWEB
 
    volumes:
    - ./templates/site.template:/etc/nginx/templates
    - ./contenuweb:/usr/share/nginx/html:rw
 
    ports:
    - "8080:80"
 
    environment:
    - NGINX_HOST=monServeurWeb.com
    - NGINX_PORT=80  # N'est pas utilisée dans cet exemple